version: '3'

services:
  kayoko-client:
    image: ghcr.io/gokoro/kayoko-client:latest
    volumes:
      - output:/app/output
    env_file: 
      - client.env

  kayoko-rvc:
    image: ghcr.io/gokoro/kayoko-rvc:latest
    volumes:
      - output:/app/rvc/voice-output
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]


volumes:
  output:
